version: '3'
services:
    nginx:
        build:
            context: ./nginx_mediaserver
            dockerfile: Dockerfile
        container_name: mediaserver
        restart: always # 컨테이너가 중지될 때마다 항상 재시작합니다.
        volumes:
            - ./nginx_mediaserver/nginx.conf:/usr/local/nginx/conf/nginx.conf
            # nginx log 와 동기화
            - ./nginx_mediaserver/logs:/usr/local/nginx/logs/
            # hls 설정으로 인한 파일삭제로 인해 그 삭제를 막기 위해 로컬 호스트 파일은 :ro 를 붙여 읽기 전용으로 설정
            - ./uploads/video:/app/media/hls:ro
        ports:
            - '8080:8080'
        networks:
            - platform-network
networks:
    platform-network:
        name: platform-network
        driver: bridge
