version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: video_backend
        # ports:
        #     - '3010:3010'
        volumes:
            - ./uploads:/app/project/uploads
        depends_on:
            - mariadb # MariaDB가 시작된 후에 backend 시작
        networks:
            - platform-network
    webserver:
        build:
            context: ./nginx_webserver
            dockerfile: Dockerfile
        container_name: webserver
        restart: always # 컨테이너가 중지될 때마다 항상 재시작합니다.
        volumes:
            - ./nginx_webserver/default.conf:/etc/nginx/conf.d/default.conf
            # nginx log 와 동기화
            - ./nginx_webserver/logs:/var/log/nginx
        ports:
            - '80:80'
            - '3010:3010'
        networks:
            - platform-network
    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        restart: unless-stopped # 컨테이너가 중지되지 않은 경우에만 재시작합니다.
        container_name: mariadb
        # 최대 메모리양 설정 : 128m : 적은양 간단한 작업식 적절
        mem_limit: 128m
        ports:
            - '63110:3306'
        volumes:
            - ./mariadb/maria_data:/var/lib/mysql
            - ./mariadb/sqls/:/docker-entrypoint-initdb.d/
        # 환경 변수 셋팅시에는 `-` 는 생략한다.
        environment:
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_ROOT_PASSWORD: ${DB_PASS}
            TZ: ${TIME_ZONE}
        networks:
            - platform-network
networks:
    platform-network:
        name: platform-network
        driver: bridge
