version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: video_backend
        ports:
            - '3100:3100'
        # 최대 메모리양 설정 : 128m : 적은양 간단한 작업식 적절
        mem_limit: 128m

    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: mariadb
        ports:
            - '63100:3306'
        volumes:
            - ./mariadb/maria_data:/var/lib/mysql
            - ./mariadb/sqls/:/docker-entrypoint-initdb.d/
        environment:
            MARIADB_DATABASE: ${DB_HOST}
            MARIADB_ROOT_PASSWORD: ${DB_PASS}
